test clear ver

diff --git a/.bin/terraform/tf-mv-file b/.bin/terraform/tf-mv-file
--- a/.bin/terraform/tf-mv-file
+++ b/.bin/terraform/tf-mv-file
@@ -7,13 +7,23 @@
 
 set -eu
 
-OUTPUT_LIST=_output_list
-OUTPUT_TO=_outputs.tf
+sId=$(cat /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 5 | head -n 1)
+
+# refered file
 OUTPUTS=outputs.tf
+
+# generating files
+OUTPUT_TO=_"$sId"_outputs.tf
+REMOTE_STATE=_"$sId"_remote_state.tf
+DATA_TF=_"$sId"_data.tf
+LOCALS_TF=_"$sId"_locals.tf
+TFSTATE=_"$sId"_tfstate
+
+# temporary files
+TFSTATE_LIST=_"$sId"_tfstate_list
+DEPENDENCY_GRAPH_DST_TO_SRC=_"$sId"_dependency_graph_dst_to_src
+DEPENDENCY_GRAPH_SRC_TO_DST=_"$sId"_dependency_graph_src_to_dst
 OVERRIDE=override.tf
-REMOTE_STATE=_remote_state.tf
-TFSTATE=tfstate
-TFSTATE_LIST=_tfstate_list
 
 function usage() {
     echo "Usage: $1 [-y] -s <src pj dir> -d <dst pj dir> [-f <target files>]"
@@ -49,62 +59,90 @@ function _popd {
 }
 
 function state_mv {
-    local srcPjDir=$1
-    local dstPjDir=$2
+    local src_pj_dir=$1
+    local dst_pj_dir=$2
     local rsc=$3
     local dryRun=$4
 
-    echo terraform state mv -state="${srcPjDir}"/$TFSTATE -state-out="${dstPjDir}"/$TFSTATE \'"$rsc"\' \'"$rsc"\'
+    echo terraform state mv -state="${src_pj_dir}"/$TFSTATE -state-out="${dst_pj_dir}"/$TFSTATE \'"$rsc"\' \'"$rsc"\'
     if [[ $dryRun == "false" ]]; then
-        terraform state mv -state="${srcPjDir}"/$TFSTATE -state-out="${dstPjDir}"/$TFSTATE $rsc $rsc
+        terraform state mv -state="${src_pj_dir}"/$TFSTATE -state-out="${dst_pj_dir}"/$TFSTATE $rsc $rsc
     fi
 }
 
-function output_mv {
-    local srcPjDir=$1
-    local dstPjDir=$2
+# create reference from dst pj to src pj
+function replace_to_indirect_for_src {
+    local src_pj_dir=$1
+    local dst_pj_dir=$2
     local rsc=$3
     local stateAlias=$4
     local dryRun=$5
 
-    if [[ -f $srcPjDir/$OUTPUT_LIST ]]; then
-        while read kv; do
-            local k=$(echo $kv | cut -d, -f1)
-            local v=$(echo $kv | cut -d, -f2)
+    # keep value reference between src and dst
+    while read -r field; do
+        local file=$(echo $field | cut -d, -f1)
+        for var in $(echo $field | cut -d, -f2- | tr ',' ' '); do
+            local label=$(echo $var | gsed -e 's/\./_/g' -e 's/^module.//g')
 
-            local label=$(echo $k | cut -d. -f2)
-
-            echo "echo \"output \\\"$label\\\" {\\n value = $v \\n}\" >> $dstPjDir/$OUTPUT_TO"
-            echo hcledit attribute set $k.value data.terraform_remote_state.$stateAlias.outputs.$label --update --file $srcPjDir/$OUTPUTS
-
+            echo "echo \"output \\\"$label\\\" {\\n value = $var \\n}\" >> $dst_pj_dir/$OUTPUT_TO"
+            echo "gsed -i s/$var/data.terraform_remote_state.$stateAlias.outputs.$label/g $src_pj_dir/$file"
             if [[ $dryRun == "false" ]]; then
-                echo "output \"$label\" {\n value = $v \n}" >> "$dstPjDir"/$OUTPUT_TO
-                hcledit attribute set $k.value data.terraform_remote_state.$stateAlias.outputs.$label --update --file $srcPjDir/$OUTPUTS
+                if ! grep -q "output \"$label\"" "$dst_pj_dir"/$OUTPUT_TO; then
+                    echo "output \"$label\" {\n value = $var \n}" >> "$dst_pj_dir"/$OUTPUT_TO
+                fi
+                gsed -i "s/$var/data.terraform_remote_state.$stateAlias.outputs.$label/g" $src_pj_dir/$file
             fi
-        done < <(grep "$rsc" "$srcPjDir"/$OUTPUT_LIST)
-    fi
+        done
+    done < <(cat $src_pj_dir/$DEPENDENCY_GRAPH_DST_TO_SRC | jq -r ".[] | select(.name == \"$rsc\") | [.ref.file, .ref.vars[]] |@csv" | sed 's/\"//g')
+}
+
+function replace_to_indirect_for_dst {
+    local src_pj_dir=$1
+    local dst_pj_dir=$2
+    local tgtFile=$3
+    local stateAlias=$4
+    local dryRun=$5
+
+    while read -r field; do
+        for var in $(echo $field | tr ',' ' '); do
+            local label=$(echo $var | gsed -e 's/\./_/g' -e 's/^module.//g')
+
+            echo "echo \"output \\\"$label\\\" {\\n value = $var \\n}\" >> $src_pj_dir/$OUTPUT_TO"
+            echo "gsed -i s/$var/data.terraform_remote_state.$stateAlias.outputs.$label/g $dst_pj_dir/$tgtFile"
+            if [[ $dryRun == "false" ]]; then
+                if ! grep -q "output \"$label\"" "$src_pj_dir"/$OUTPUT_TO; then
+                    echo "output \"$label\" {\n value = $var \n}" >> "$src_pj_dir"/$OUTPUT_TO
+                fi
+                gsed -i "s/$var/data.terraform_remote_state.$stateAlias.outputs.$label/g" $dst_pj_dir/$tgtFile
+            fi
+        done
+    done < <(cat $src_pj_dir/$DEPENDENCY_GRAPH_SRC_TO_DST | jq -r ".[] | select(.ref.file == \"$tgtFile\") | [.ref.vars[]] |@csv" | sed 's/\"//g')
 }
 
 function create_file_remote_state_ref {
+    local stateAlias=$1
+    local filePath=$2
+
     cat << EOF
-data "terraform_remote_state" "$1" {
+data "terraform_remote_state" "$stateAlias" {
   backend = "local"
 
   config = {
-    path = "$2"
+    path = "$filePath"
   }
 }
 EOF
 }
 
 function create_s3_remote_state_ref {
+    local stateAlias=$1
     local tgtProviderFile=$2
     local bucket=$(hcledit attribute get terraform.backend.s3.bucket < $tgtProviderFile)
     local key=$(hcledit attribute get terraform.backend.s3.key < $tgtProviderFile)
     local region=$(hcledit attribute get terraform.backend.s3.region < $tgtProviderFile)
 
     cat << EOF
-data "terraform_remote_state" "$1" {
+data "terraform_remote_state" "$stateAlias" {
   backend = "s3"
 
   config = {
@@ -117,45 +155,33 @@ EOF
 }
 
 function init_pj {
-    local pjDir=$1
-    _pushd "$pjDir" || exit
+    local pj_dir=$1
+    _pushd "$pj_dir" || exit
 
     if [ ! -f provider.tf ]; then
-        echo "error: provider.tf not found in $pjDir"
+        echo "error: provider.tf not found in $pj_dir"
         exit 1
     fi
 
-    terraform init
+    terraform init > /dev/null
+    terraform refresh > /dev/null
     terraform state pull > $TFSTATE
     terraform state list > $TFSTATE_LIST
-
-    cat *.tf | sed '$ s/^}$/}\n/g' | hcledit block get output > __output
-
-    echo > $OUTPUT_LIST
-    while read b; do
-      v=$(hcledit attribute get $b.value < __output)
-      if [[ $(echo $v | wc -l) -ne 1 ]]; then
-        echo "error: fail to create output list, invalid output value detected\n$b, $v"
-        exit 1
-      fi
-      echo $b, $v >> $OUTPUT_LIST
-    done < <(hcledit block list < __output)
-
-    rm __output
 
     _popd || exit
 }
 
 function check_nodiff {
-    local pjDir=$1
+    local pj_dir=$1
 
-    _pushd "$pjDir" || exit
+    _pushd "$pj_dir" || exit
     override_backend
-    terraform init --reconfigure
-    if terraform plan --state=$TFSTATE -detailed-exitcode; then
-        echo "[ok] no change on $pjDir"
+    terraform init --reconfigure > /dev/null
+    terraform refresh --state=$TFSTATE > /dev/null
+    if terraform plan --state=$TFSTATE -detailed-exitcode > /dev/null; then
+        echo "[ok] no change on $pj_dir"
     else
-        echo "[error] change detected or plan failed on $pjDir"
+        echo "[error] plan failed on $pj_dir"
         restore_backend_from_override
         exit 1
     fi
@@ -165,97 +191,123 @@ function check_nodiff {
 
 dryRun="true"
 
-srcPjDir=
-dstPjDir=
-tgtTfFiles=
+src_pj_dir=
+dst_pj_dir=
+target_files=
 
 while getopts ys:d:f:h flag
 do
     case "${flag}" in
         y) dryRun="false";;
-        s) srcPjDir=${OPTARG};;
-        d) dstPjDir=${OPTARG};;
-        f) tgtTfFiles=${OPTARG};;
+        s) src_pj_dir=${OPTARG};;
+        d) dst_pj_dir=${OPTARG};;
+        f) target_files=${OPTARG};;
         h) usage $0; exit 0;;
     esac
 done
 
 echo "dry run: $dryRun"
 
-if [[ ! -d "$srcPjDir" ]]; then
-  echo "error: invalid src pj directory $srcPjDir"
+if [[ ! -d "$src_pj_dir" ]]; then
+  echo "error: invalid src pj directory $src_pj_dir"
   exit 1
 fi
 
-if [[ ! -d "$dstPjDir" ]]; then
-  echo "error: invalid dst pj directory $dstPjDir"
+if [[ ! -d "$dst_pj_dir" ]]; then
+  echo "error: invalid dst pj directory $dst_pj_dir"
   exit 1
 fi
 
-srcPjDir=$(echo "$srcPjDir" | sed 's/\/$//')
-dstPjDir=$(echo "$dstPjDir" | sed 's/\/$//')
+src_pj_dir=$(echo "$src_pj_dir" | sed 's/\/$//')
+dst_pj_dir=$(echo "$dst_pj_dir" | sed 's/\/$//')
 
-echo "initializing dstDir: $dstPjDir ..."
-init_pj "$dstPjDir"
+stateAlias=$(basename $src_pj_dir)_$sId
 
-echo "initializing srcDir: $srcPjDir ..."
-init_pj "$srcPjDir"
-relpath=$(grealpath -m --relative-to="$srcPjDir" "$dstPjDir")/$TFSTATE
-stateAlias=$(basename $dstPjDir)_$(cat /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 5 | head -n 1)
-create_file_remote_state_ref $stateAlias $relpath > "$srcPjDir"/$REMOTE_STATE
+echo "initializing dstDir: $dst_pj_dir ..."
+init_pj "$dst_pj_dir"
+relpath=$(grealpath -m --relative-to="$dst_pj_dir" "$src_pj_dir")/$TFSTATE
 
-if [[ "$tgtTfFiles" == "" ]]; then
-  _pushd "$srcPjDir" || exit
-  tgtTfFiles=$(find -- *.tf | peco --prompt "select target files")
+echo "initializing srcDir: $src_pj_dir ..."
+init_pj "$src_pj_dir"
+relpath=$(grealpath -m --relative-to="$src_pj_dir" "$dst_pj_dir")/$TFSTATE
+
+if [[ "$target_files" == "" ]]; then
+  _pushd "$src_pj_dir" || exit
+  target_files=$(find -- *.tf | peco --prompt "select target files")
   _popd || exit
 fi
+if [[ "$target_files" == "" ]]; then
+    echo "no target"
+    exit
+fi
 
-for tgtTf in $(echo $tgtTfFiles); do
-  for rsc in $(hcledit block list < "${srcPjDir}/$tgtTf" | grep -e "^resource" -e "^module" | sort); do
-    if [[ $(hcledit attribute get "${rsc}.for_each" < "${srcPjDir}/$tgtTf" | wc -l) -eq 0 ]]; then
-      # no for_each resource
-      rsc=${rsc//#resource./}
-      state_mv "$srcPjDir" "$dstPjDir" "$rsc" "$dryRun"
-      output_mv "$srcPjDir" "$dstPjDir" "$rsc" "$stateAlias" "$dryRun"
-    else
-      # for_each resource
-      rsc=${rsc//#resource./}
+#
+_pushd "$src_pj_dir" || exit
+echo "creating dep graph ..."
+tf-dependency $(echo $target_files | tr '\n' ' ') | jq . > $DEPENDENCY_GRAPH_DST_TO_SRC
+tf-dependency $(find -- *.tf | grep -v $target_files | tr '\n' ' ') | jq . > $DEPENDENCY_GRAPH_SRC_TO_DST
+_popd
 
-      while read -r each_rsc; do
-        state_mv "$srcPjDir" "$dstPjDir" "$each_rsc" "$dryRun"
-        output_mv "$srcPjDir" "$dstPjDir" "$each_rsc" "$stateAlias" "$dryRun"
-      done < <(grep "$rsc" "${srcPjDir}"/$TFSTATE_LIST)
+# state mv
+for tgtTf in $(echo $target_files); do
+    for rsc in $(hcledit block list < "${src_pj_dir}/$tgtTf" | grep -e "^resource" -e "^module" | sort); do
+        if [[ $(hcledit attribute get "${rsc}.for_each" < "${src_pj_dir}/$tgtTf" | wc -l) -eq 0 ]]; then
+            # no for_each resource
+            rsc=${rsc//#resource./}
+            state_mv "$src_pj_dir" "$dst_pj_dir" "$rsc" "$dryRun"
+            replace_to_indirect_for_src "$src_pj_dir" "$dst_pj_dir" "$rsc" "$stateAlias" "$dryRun"
+        else
+            # for_each resource
+            rsc=${rsc//#resource./}
+
+            while read -r each_rsc; do
+                state_mv "$src_pj_dir" "$dst_pj_dir" "$each_rsc" "$dryRun"
+                replace_to_indirect_for_src "$src_pj_dir" "$dst_pj_dir" "$each_rsc" "$stateAlias" "$dryRun"
+            done < <(grep "$rsc" "${src_pj_dir}"/$TFSTATE_LIST)
+        fi
+    done
+
+    if [[ $dryRun == "false" ]]; then
+        mv ${src_pj_dir}/${tgtTf} ${dst_pj_dir}/${tgtTf}
     fi
-  done
 
-  if [[ $dryRun == "true" ]]; then
-      continue
-  fi
-
-  mv ${srcPjDir}/${tgtTf} ${dstPjDir}/${tgtTf}
-
-  check_nodiff "$dstPjDir"
-  check_nodiff "$srcPjDir"
+    replace_to_indirect_for_dst "$src_pj_dir" "$dst_pj_dir" "$tgtTf" "$stateAlias" "$dryRun"
 done
 
 
 if [[ $dryRun == "false" ]]; then
-    create_s3_remote_state_ref $stateAlias "$dstPjDir"/provider.tf >> "$srcPjDir"/$REMOTE_STATE
+    cat "$src_pj_dir"/*.tf | hcledit block get data   > "$dst_pj_dir"/"$DATA_TF"
+    cat "$src_pj_dir"/*.tf | hcledit block get locals > "$dst_pj_dir"/"$LOCALS_TF"
+
+    create_file_remote_state_ref $stateAlias $relpath > "$dst_pj_dir"/$REMOTE_STATE
+    create_file_remote_state_ref $stateAlias $relpath > "$src_pj_dir"/$REMOTE_STATE
+
+    check_nodiff "$dst_pj_dir"
+    check_nodiff "$src_pj_dir"
+fi
+
+if [[ $dryRun == "false" ]]; then
+    create_s3_remote_state_ref $stateAlias "$dst_pj_dir"/provider.tf > "$src_pj_dir"/$REMOTE_STATE
+    create_s3_remote_state_ref $stateAlias "$src_pj_dir"/provider.tf > "$dst_pj_dir"/$REMOTE_STATE
 
     echo "# state and file move completed"
     echo "# please check the result and run following command to apply"
     echo
-    echo "cd $srcPjDir"
+    echo "cd $src_pj_dir"
     echo "terraform state push $TFSTATE"
     echo "terraform init --reconfigure"
     echo "terraform plan"
-    echo "git add $tgtFiles"
+    echo "git add $target_files"
     echo "git add $REMOTE_STATE"
     echo
-    echo "cd $dstPjDir"
+    echo "cd $dst_pj_dir"
     echo "terraform state push $TFSTATE"
     echo "terraform init --reconfigure"
     echo "terraform plan"
-    echo "git add $tgtFiles"
+    echo "git add $target_files"
     echo "git add $OUTPUT_TO"
 fi
+
+# cleanup
+rm -f $src_pj_dir/$TFSTATE_LIST $src_pj_dir/$DEPENDENCY_GRAPH_DST_TO_SRC $src_pj_dir/$DEPENDENCY_GRAPH_SRC_TO_DST
+rm -f $dst_pj_dir/$TFSTATE_LIST
