modiry

diff --git a/.bin/terraform/tf-mv-file b/.bin/terraform/tf-mv-file
--- a/.bin/terraform/tf-mv-file
+++ b/.bin/terraform/tf-mv-file
@@ -8,9 +8,10 @@
 set -eu
 
 OUTPUT_LIST=_output_list
-OUTPUT=_output
-OUTPUT_TO=_output.tf
+OUTPUT_TO=_outputs.tf
+OUTPUTS=outputs.tf
 OVERRIDE=override.tf
+REMOTE_STATE=_remote_state.tf
 TFSTATE=tfstate
 TFSTATE_LIST=_tfstate_list
 
@@ -69,11 +70,11 @@ function output_mv {
             local v=$(echo $kv | cut -d, -f2)
 
             echo "terraform output $k { value = $v } >> $dstPjDir/$OUTPUT_TO"
-            echo hcledit attribute set $k.value data.terraform_remote_state.$stateAlias.outputs.$v --update --file $srcPjDir/output.tf
+            echo hcledit attribute set $k.value data.terraform_remote_state.$stateAlias.outputs.$v --update --file $srcPjDir/$OUTPUTS
 
             if [[ $dryRun == "false" ]]; then
                 echo "terraform output \"$k\" { value = $v }" >> "$dstPjDir"/$OUTPUT_TO
-                hcledit attribute set $k.value data.terraform_remote_state.$stateAlias.outputs.$v --update --file $srcPjDir/output.tf
+                hcledit attribute set $k.value data.terraform_remote_state.$stateAlias.outputs.$v --update --file $srcPjDir/$OUTPUTS
             fi
         done < <(grep "$rsc" "$srcPjDir"/$OUTPUT_LIST)
     fi
@@ -99,17 +100,37 @@ function init_pj {
     terraform state pull > $TFSTATE
     terraform state list > $TFSTATE_LIST
 
-    cat *.tf | hcledit block get output > $OUTPUT
+    cat *.tf | sed '$ s/^}$/}\n/g' | hcledit block get output > __output
+
     echo > $OUTPUT_LIST
     while read b; do
-      v=$(cat *.tf | hcledit attribute get $b.value)
-      if [[ echo $v | wc -l -neq 1 ]]; then
+      v=$(hcledit attribute get $b.value < __output)
+      if [[ $(echo $v | wc -l) -neq 1 ]]; then
         echo "error: fail to create output list, invalid output value $b, $v"
         exit 1
       fi
       echo $b, $v >> $OUTPUT_LIST
-    done < <(hcledit block list < $OUTPUT)
+    done < <(hcledit block list < __output)
 
+    rm __output
+
+    _popd || exit
+}
+
+function check_nodiff {
+    local pjDir=$1
+
+    _pushd "$pjDir" || exit
+    override_backend
+    terraform init --reconfigure
+    if terraform plan --state=$TFSTATE -detailed-exitcode; then
+        echo "[ok] no change on $pjDir"
+    else
+        echo "[error] change detected or plan failed on $pjDir"
+        restore_backend_from_override
+        exit 1
+    fi
+    restore_backend_from_override
     _popd || exit
 }
 
@@ -152,7 +173,7 @@ echo "initializing srcDir: $srcPjDir ..."
 init_pj "$srcPjDir"
 relpath=$(grealpath -m --relative-to="$srcPjDir" "$dstPjDir")/$TFSTATE
 stateAlias=$(basename $dstPjDir)_$(cat /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 5 | head -n 1)
-create_remote_state_ref $stateAlias $relpath
+create_remote_state_ref $stateAlias $relpath "$srcPjDir"/$REMOTE_STATE
 
 if [[ "$tgtTfFiles" == "" ]]; then
   _pushd "$srcPjDir" || exit
@@ -166,55 +187,39 @@ for tgtTf in $tgtTfFiles; do
       # no for_each resource
       rsc=${rsc//#resource./}
       state_mv "$srcPjDir" "$dstPjDir" "$rsc" "$dryRun"
-      output_mv "$srcPjDir" "$dstPjDir" "$rsc" "$dryRun"
+      output_mv "$srcPjDir" "$dstPjDir" "$rsc" "$stateAlias" "$dryRun"
     else
       # for_each resource
       rsc=${rsc//#resource./}
 
       while read -r each_rsc; do
         state_mv "$srcPjDir" "$dstPjDir" "$each_rsc" "$dryRun"
-        output_mv "$srcPjDir" "$dstPjDir" "$each_rsc" "$dryRun"
+        output_mv "$srcPjDir" "$dstPjDir" "$each_rsc" "$stateAlias" "$dryRun"
       done < <(grep "$rsc" "${srcPjDir}"/$TFSTATE_LIST)
     fi
   done
 
+  if [[ $dryRun == "true" ]]; then
+      continue
+  fi
+
   mv ${srcPjDir}/${tgtTf} ${dstPjDir}/${tgtTf}
 
-  _pushd "$dstPjDir" || exit
-  override_backend
-  terraform init --reconfigure
-  if terraform plan --state=$TFSTATE -detailed-exitcode; then
-    echo "[ok] no change on $dstPjDir"
-  else
-    echo "[error] change detected or plan failed on $dstPjDir"
-    restore_backend_from_override
-    exit 1
-  fi
-  restore_backend_from_override
-  _popd || exit
-
-  _pushd "$srcPjDir" || exit
-  override_backend
-  terraform init --reconfigure
-  if terraform plan --state=$TFSTATE -detailed-exitcode; then
-    echo "[ok] no change on $srcPjDir"
-  else
-    echo "[error] change detected or plan failed on $srcPjDir"
-    restore_backend_from_override
-    exit 1
-  fi
-  restore_backend_from_override
-  _popd || exit
+  check_nodiff "$dstPjDir"
+  check_nodiff "$srcPjDir"
 done
 
-echo "state and file move completed"
-echo "please check the result and run following command to apply"
-echo
-echo "cd $srcPjDir"
-echo "terraform state push $TFSTATE"
-echo "terraform init --reconfigure"
-echo "terraform plan"
-echo "cd $dstPjDir"
-echo "terraform state push $TFSTATE"
-echo "terraform init --reconfigure"
-echo "terraform plan"
+
+if [[ $dryRun == "false" ]]; then
+    echo "state and file move completed"
+    echo "please check the result and run following command to apply"
+    echo
+    echo "cd $srcPjDir"
+    echo "terraform state push $TFSTATE"
+    echo "terraform init --reconfigure"
+    echo "terraform plan"
+    echo "cd $dstPjDir"
+    echo "terraform state push $TFSTATE"
+    echo "terraform init --reconfigure"
+    echo "terraform plan"
+fi
